# Generated by Django 6.0.2 on 2026-02-09 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название здания/рынка/территории')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Здание/Рынок/Территория',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название договора')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Файл договора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Договор аренды',
                'verbose_name_plural': 'Договоры аренды',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назване категории')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория товаров',
                'verbose_name_plural': 'Категории товаров',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название компании/ФИО')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Арендатор',
                'verbose_name_plural': 'Арендаторы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pavilion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название павильона')),
                ('row', models.CharField(blank=True, max_length=100, verbose_name='Ряд')),
                ('area', models.DecimalField(decimal_places=2, default=45.0, max_digits=8, verbose_name='Площадь (кв.м.)')),
                ('status', models.CharField(choices=[('free', 'Свободен'), ('rented', 'Арендован'), ('reserved', 'Забронирован'), ('repair', 'На ремонте')], default='free', max_length=20, verbose_name='Статус')),
                ('electricity_meter_number', models.CharField(blank=True, max_length=50, verbose_name='Номер счетчика')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pavilions', to='pavilions.building', verbose_name='Здание/Рынок/Территория')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pavilions.contract', verbose_name='Договор аренды')),
                ('product_categories', models.ManyToManyField(blank=True, to='pavilions.productcategory', verbose_name='Категории товаров')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pavilions.tenant', verbose_name='Арендатор')),
            ],
            options={
                'verbose_name': 'Павильон',
                'verbose_name_plural': 'Павильоны',
                'ordering': ['building', 'row', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ElectricityConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('meter_reading', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Показания счетчика (кВт ч)')),
                ('consumption', models.DecimalField(decimal_places=2, help_text='Разница с предыдущим периодом', max_digits=20, verbose_name='Потребление (кВТ ч)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('pavilion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electricity_consumptions', to='pavilions.pavilion', verbose_name='Павильон')),
            ],
            options={
                'verbose_name': 'Потребление электроэнергии',
                'verbose_name_plural': 'Потребление электроэнергии',
                'ordering': ['-date'],
                'unique_together': {('pavilion', 'date')},
            },
        ),
        migrations.AddConstraint(
            model_name='pavilion',
            constraint=models.UniqueConstraint(fields=('building', 'name'), name='unique_pavilion_per_building'),
        ),
    ]
