# Generated by Django 6.0.2 on 2026-02-09 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pavilions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['name'], 'verbose_name': 'Здание/Рынок/Территория', 'verbose_name_plural': 'Здания/Рынки/Территории'},
        ),
    ]
