# Generated by Django 6.0.2 on 2026-02-10 07:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pavilions', '0002_alter_building_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pavilion',
            name='electricity_meter_number',
        ),
        migrations.AlterField(
            model_name='pavilion',
            name='area',
            field=models.DecimalField(decimal_places=2, default=45.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Площадь (кв.м.)'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название категории'),
        ),
        migrations.CreateModel(
            name='ElectricityMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_number', models.CharField(db_index=True, help_text='Номер по документам', max_length=50, verbose_name='Номер счетчика')),
                ('serial_number', models.CharField(blank=True, db_index=True, help_text='Серийный номер производителя', max_length=100, verbose_name='Серийный номер')),
                ('location', models.CharField(blank=True, help_text='Где установлен счетчик', max_length=200, verbose_name='Расположение')),
                ('last_verified_hours_ago', models.IntegerField(blank=True, help_text='Сколько часов прошло с последней проверки', null=True, verbose_name='Часов с последней проверки')),
                ('comment', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('pavilion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electricity_meters', to='pavilions.pavilion', verbose_name='Павильон')),
            ],
            options={
                'verbose_name': 'Счетчик электроэнергии',
                'verbose_name_plural': 'Счетчики электроэнергии',
                'ordering': ['pavilion', 'meter_number'],
            },
        ),
        migrations.CreateModel(
            name='ElectricityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата снятия показаний')),
                ('meter_reading', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Показания счетчика (кВт·ч)')),
                ('consumption', models.DecimalField(blank=True, decimal_places=2, help_text='Рассчитывается автоматически', max_digits=20, null=True, verbose_name='Потребление за период (кВт·ч)')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='pavilions.electricitymeter', verbose_name='Счетчик')),
            ],
            options={
                'verbose_name': 'Показание счетчика',
                'verbose_name_plural': 'Показания счетчиков',
                'ordering': ['-date', 'meter'],
            },
        ),
        migrations.DeleteModel(
            name='ElectricityConsumption',
        ),
        migrations.AddConstraint(
            model_name='electricitymeter',
            constraint=models.UniqueConstraint(fields=('meter_number',), name='unique_meter_number'),
        ),
        migrations.AddIndex(
            model_name='electricityreading',
            index=models.Index(fields=['meter', 'date'], name='pavilions_e_meter_i_c1d7a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='electricityreading',
            unique_together={('meter', 'date')},
        ),
    ]
