# Generated by Django 6.0.2 on 2026-02-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pavilions', '0004_electricitymeter_pavilions'),
    ]

    operations = [
        migrations.AddField(
            model_name='pavilion',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Дополнительные характеристики павильона', verbose_name='Теги павильона'),
        ),
    ]
