# Generated by Django 6.0.2 on 2026-02-25 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pavilions', '0006_tenant_inn'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricShield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название щита')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Электрощиток',
                'verbose_name_plural': 'Электрощитки',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='pavilion',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pavilion', to='pavilions.tenant', verbose_name='Арендатор'),
        ),
        migrations.AddField(
            model_name='electricitymeter',
            name='electric_shield',
            field=models.ForeignKey(blank=True, help_text='К какому электрощиту подключён этот счётчик', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meters', to='pavilions.electricshield', verbose_name='Электрощиток'),
        ),
    ]
